#!/usr/bin/env python
import sys
from clint.textui import colored
from Launch.Launch import Launch
from Prompt.Prompt import Prompt

if __name__ == "__main__":
	prompt=Prompt()
	launch=Launch()

	if len(sys.argv) == 1:
		Launch.show_logo4()
		print colored.yellow("usage: ")+colored.magenta("./gladius -c server-info.config\n")
		sys.exit()

	args=launch.get_args()
	launch.show_logo2()
	prompt.prompt = 'Gladius>'
	prompt.cmdloop()